version: 2
jobs:
  build:
    working_directory: /root/go/src/github.com/sheerun/firebasehelpers
    environment:
      - GOPATH: "/root/go"
    docker:
      - image: golang:1.8
    steps:
      - checkout
      - run: go get
      - run: go test
